// This file is generated

I_birth_place_0 = [
"Lewiston, Cache, Utah, United States of America",
"Lisbon, Grafton, New Hampshire, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Saint Charles, St. Charles, Missouri, United States of America",
"",
"",
"Mansfield, Nottinghamshire, East Midlands, England",
"Alameda, Alameda, California, United States of America",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Granville, Hampden, Massachusetts, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Heber's Spring, Platte, Wyoming, New York, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Shamokin, Northumberland, Pennsylvania, United States of America",
"Germany",
"",
"Huntington, Lorain, Ohio, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Lyman, Uinta, Wyoming, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Derbyshire, East Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Staffordshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Ilkeston, Derbyshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Bedford, Bedfordshire, East, England",
"Cossall, Nottinghamshire, East Midlands, England",
"Ilkeston, Derbyshire, East Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Ilkeston, Derbyshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Ilkeston, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Lyman, Uinta, Wyoming, United States of America",
"Clayton le Moors, Lancashire, North West, England",
"Cuddington, Buckinghamshire, South East, England",
"Cradley, Herefordshire, West Midlands, England",
"Hartland, Niagara, New York, United States of America",
"Kanesville, Pottawattamie, Iowa, United States of America",
"New York, United States of America",
"New York, United States of America",
"Madison Township, Geauga, Ohio, United States of America",
"Willow Creek, Box Elder, Utah, United States of America",
"Willow Creek, Box Elder, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Afton, Uinta, Wyoming, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"",
"",
"",
"",
"Quorn, Leicestershire, East Midlands, England",
"Liverpool, Lancashire, North West, England",
"Quorn, Leicestershire, East Midlands, England",
"Dublin, Dublin, Leinster, Ireland",
"Jacksonville, Duval, Florida, United States of America",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Liverpool, Lancashire, North West, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Liverpool, Lancashire, North West, England",
"Quorn, Leicestershire, East Midlands, England",
"Chattanooga, Hamilton, Tennessee, United States of America",
"Liverpool, Lancashire, North West, England",
"Kilby, Leicestershire, East Midlands, England",
"Jacksonville, Duval, Florida, United States of America",
"Chattanooga, Hamilton, Tennessee, United States of America",
"Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Brixton, Lambeth, Surrey, London, England",
"London, London, England",
"London, London, England",
"London, London, England",
"Bedford, Bedfordshire, East, England",
"Pimlico, Middlesex, South East, England",
"Clapham Common, London, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bedford, Bedfordshire, East, England",
"Holborn, Middlesex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Louth, Lincolnshire, East Midlands, England",
"Bedford, Bedfordshire, East, England",
"",
"Far West, Caldwell, Missouri, United States of America",
"Fort Ann, Washington, New York, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Fort Ann, Washington, New York, United States of America",
"Florence, Erie, Ohio, United States of America",
"Liberty, Clay, Missouri, United States of America",
"Galon, Washington, New York, United States of America",
"Queensbury, Warren, New York, United States of America",
"Fort Ann, Washington, New York, United States of America",
"Galvin, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Stowell, Somerset, South West England, England",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Stockport, Cheshire, North West, England",
"Thornley, Lancashire, North West, England",
"Patrick, Isle of Man",
"Mercer, Kentucky, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"Norfolk, Litchfield, Connecticut, United States of America",
"Wethersfield Springs, Wyoming, New York, United States of America",
"Wethersfield Springs, Wyoming, New York, United States of America",
"Wethersfield Springs, Wyoming, New York, United States of America",
"New York, United States of America",
"Louth, Lincolnshire, East Midlands, England",
"Oneida, Idaho, United States of America",
"Weston, Franklin, Idaho, United States of America",
"Halifax, Yorkshire, Yorkshire and the Humber, England",
"Oneida, Idaho, United States of America",
"Weston, Franklin, Idaho, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Springville, Utah, Utah, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Kinderhook, Columbia, New York, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Kingsbury, Washington, New York, United States of America",
"Kingsbury, Washington, New York, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Bolton, Warren, New York, United States of America",
"Allegany, Cattaraugus, New York, United States of America",
"",
"",
"",
"",
"",
"",
"Amboy, Oswego, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Caineville, Wayne, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Aldridge, Wayne, Utah, United States of America",
"Caineville, Wayne, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Springville, Utah, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Tiverton, Newport, Rhode Island, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Amboy, Oswego, New York, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Amboy, Oswego, New York, United States of America",
"Williamstown, Oswego, New York, United States of America",
"Tiverton, Newport, Rhode Island, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Springville, Utah, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Amboy, Oswego, New York, United States of America",
"Lyman, Wayne, Utah, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Kirtland, Lake, Ohio, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Aldridge, Wayne, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Aldridge, Wayne, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Loa, Wayne, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Amboy, Oswego, New York, United States of America",
"",
"Almy, Uinta, Wyoming, United States of America",
"Polmont, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Spring Valley, Uinta, Wyoming, United States of America",
"Spring Valley, Uinta, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Diamondville, Uinta, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Polmont, Stirlingshire, Scotland",
"Almy, Uinta, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Almy, Uinta, Wyoming, United States of America",
"Almy, Uinta, Wyoming, United States of America",
"Uinta, Wyoming, United States of America",
"Glencoe, Lincoln, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Almy, Uinta, Wyoming, United States of America",
"Edmonton, Middlesex, South East, England",
"",
"",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Greenville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Greenville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Quarrington, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"",
"",
"",
"Draper, Salt Lake, Utah, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Redstone, Fayette, Pennsylvania, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Sterling, Windham, Connecticut, United States of America",
"Wield, Hampshire, South East, England",
"Chester, Delaware, Pennsylvania, United States of America",
"",
"Leigh, Worcestershire, West Midlands, England",
"Cedar City, Iron, Utah, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Moravia, Cayuga, New York, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Dutchess, New York, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Winter Quarters, Douglas, Nebraska, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"East Fishkill, Dutchess, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Cedar City, Iron, Utah, United States of America",
"",
"",
"",
"Minersville, Beaver, Utah, United States of America",
"Lyman, Uinta, Wyoming, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Cumberland, Lincoln, Wyoming, United States of America",
"Glencoe, Lincoln, Wyoming, United States of America",
"Lyman, Uinta, Wyoming, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Bainbridge, Ross, Ohio, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Tysoe, Warwickshire, West Midlands, England",
"Holiston, Middlesex, South East, England",
"Lichfield, Staffordshire, West Midlands, England",
"",
"",
"",
"",
"Windsor, Kennebec, Maine, United States of America",
"Wethersfield, Genesee, New York, United States of America",
"Genessee, Allegany, New York, United States of America",
"Old Monkland, Lanarkshire, Scotland",
"Armadale, Linlithgowshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"Bathgate, Linlithgowshire, Scotland",
"Wilton, Roxburghshire, Scotland",
"Cadder, Lanarkshire, Scotland",
"West Calder, Edinburghshire, Scotland",
"Kilwinning, Ayrshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"Prestonpans, Haddingtonshire, Scotland",
"West Calder, Linlithgowshire, Scotland",
"West Calder, Linlithgowshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Amenia, Dutchess, New York, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Kings Norton, Worcestershire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Redford, Wayne, Michigan, United States of America",
"New York, United States of America",
"Redford, Wayne, Michigan, United States of America",
"New York, United States of America",
"Michigan, United States of America",
"Dukinfield, Cheshire, North West, England",
"Watertown, Jefferson, New York, United States of America",
"",
"Lyonshall, Herefordshire, West Midlands, England",
"Nashville, Davidson, Tennessee, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Oxford, Bannock, Idaho, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Royalston, Worcester, Massachusetts, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Lockport, Niagara, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Suffield, Portage, Ohio, United States of America",
"Sheldon, Franklin, Vermont, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Wymondham, Norfolk, East, England",
"Kilmarnock, Ayrshire, Scotland",
"Lockport, Niagara, New York, United States of America",
"Castleton, Derbyshire, East Midlands, England",
"",
"Crawfordsburn, County Down, Ireland",
"Des Moines, Polk, Iowa, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Prescott, Ontario, Canada",
"Spanish Fork, Utah, Utah, United States of America",
"",
"Fayetteville, Fayette, Georgia, United States of America",
"Florida, Montgomery, New York, United States of America",
"Heckington, Lincolnshire, East Midlands, England",
"Wilsontown, Lanarkshire, Scotland",
"",
"Montpelier, Bear Lake, Idaho, United States of America",
"Quorn, Leicestershire, East Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Winter Quarters, Douglas, Nebraska, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Logan, Cache, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kirtland, Lake, Ohio, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Watertown, Jefferson, New York, United States of America",
"Laie, Oahu, Hawaii, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Pimlico, Middlesex, South East, England",
"Stone Arabia, Montgomery, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Wymondham, Norfolk, East, England",
"Grafton, Washington, Utah, United States of America",
"Lowestoft, Suffolk, East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Great Ellingham, Norfolk, East, England",
"Saint George, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Deopham, Norfolk, East, England",
"Wymondham, Norfolk, East, England",
"Almeley, Herefordshire, West Midlands, England",
"Almeley, Herefordshire, West Midlands, England",
"Hereford, Herefordshire, West Midlands, England",
"Herefordshire, West Midlands, England",
"Pembridge, Herefordshire, West Midlands, England",
"Kings Pyon, Herefordshire, West Midlands, England",
"",
"Herefordshire, West Midlands, England",
"Almeley, Herefordshire, West Midlands, England",
"Horsley, Gloucester, South West England, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Liverpool, Lancashire, North West, England",
"Liverpool, Lancashire, North West, England",
"Liverpool, Lancashire, North West, England",
"Longford, Derbyshire, East Midlands, England",
"West Newark, Essex, New Jersey, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"",
"Quorn, Leicestershire, East Midlands, England",
"Saint Pancras, London, London, England",
"Saint Pancras, London, London, England",
"Saint Pancras, London, London, England",
"Ruabon, Denbighshire, Wales",
"Onondaga Hill, Onondaga, New York, United States of America",
"",
"Minersville, Beaver, Utah, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Parowan, Iron, Utah, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Alton, Souix, Iowa, United States of America",
"Beaver, Beaver, Utah, United States of America",
"Lima, Livingston, New York, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Missouri, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Edmonton, Middlesex, South East, England",
"Rock Hill, Worcestershire, West Midlands, England",
"Warbleton, Sussex, South East, England",
"Killin, Perthshire, Scotland",
"",
"",
"",
"",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Sempronius, Cayuga, New York, United States of America",
"",
"",
"",
"",
"",
"Saunders, Nebraska, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"St. Louis, St. Louis, Missouri, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Leigh, Worcestershire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Draper, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Springdale, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Nauvoo, Hancock, Illinois, United States of America",
"Grafton, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"St. Joseph, Buchanan, Missouri, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Florida, Montgomery, New York, United States of America",
"New York, United States of America",
"Dover, Kent, South East, England",
"Forfar, Angus, Scotland",
"Mount Pisgah, Union, Iowa, United States of America",
"",
"",
"",
"",
"",
"Wotton Under Edge, Gloucester, South West England, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Heathfield, Sussex, South East, England",
"Brighton, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Heathfield, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Brighton, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Brighton, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"",
"",
"",
"",
"",
"",
"Bountiful, Davis, Utah, United States of America",
"Rush Valley, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Rush Valley, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Rockland, Knox, Maine, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Riverdale, Franklin, Idaho, United States of America",
"Augusta, Kennebec, Maine, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Council Bluffs, Pottawattamie, Iowa, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Punka Camp, Pottawattamie, Iowa, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Manchester, Lancashire, North West, England",
"Winchester, Randolph, Indiana, United States of America",
"St. Helier, Jersey",
"Pennsylvania, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Augusta, Kennebec, Maine, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Cradley, Herefordshire, West Midlands, England",
"",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Edmonton, Middlesex, South East, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Stratford-Upon-Avon, Warwickshire, West Midlands, England",
"Stratford-Upon-Avon, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Shipley, Derbyshire, East Midlands, England",
"Bridgewater, Plymouth, Massachusetts, United States of America",
"",
"",
"Newmarket, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Coalville, Summit, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"Cwm, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Coalville, Summit, Utah, United States of America",
"Graig, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Flintshire, Wales",
"Old Cotes, Nottinghamshire, East Midlands, England",
"",
"Hebron, Washington, New York, United States of America",
"",
"Cambridge, Cambridgeshire, East, England",
"Airdrie, Lanarkshire, Scotland"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
