// This file is generated

S_author_0 = [
"Albert Edward Woolley Chisholm",
"Beatrice Easton Alleman",
"",
"",
"Brother Harward",
"Caroline Richards Woodall Howard",
"Cecilia Arthema Durfee Tolman",
"",
"Charles Rendell Mabey",
"Darrell E. Chisholm",
"Darrell E. Chisholm",
"Darrell or Marcia Chisholm",
"Dora D. Flack",
"Edmund West",
"Edmund West",
"Edson S. Packer",
"",
"",
"",
"",
"Ida M. Rollins",
"",
"",
"",
"James Rollins",
"James Rutheford",
"Janet Bradshaw",
"Janet Bradshaw",
"Janet Spilsbury Bradshaw",
"Janet Spilsbury",
"Janet Spilsbury",
"Janet Spilsbury",
"Janet Spilsbury",
"Janet Spilsbury",
"",
"",
"",
"Lizzie Poll Berret & Ida Berrett Poll",
"Madge Summers Newton",
"Marcia Durfee Chisholm",
"",
"",
"",
"",
"Robert L. Hamblin and Lorene Bradshaw",
"Robert L. Hamblin",
"Ruby Summers",
"",
"",
"The Church of Jesus Christ of Latter Day Saints",
"",
"The Media Research Bureau",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_S_author_0.js');
