// This file is generated

S_text_0 = [
"<p>\n<b>\nAuthor: \n</b>\nAlbert Edward Woolley Chisholm\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nBeatrice Easton Alleman\n</p>",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nBrother Harward\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nCaroline Richards Woodall Howard\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nCecilia Arthema Durfee Tolman\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nCharles Rendell Mabey\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nDarrell E. Chisholm\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nDarrell E. Chisholm\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nDarrell or Marcia Chisholm\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nDora D. Flack\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nEdmund West\n</p><p>\n<b>\nPublication information: \n</b>\nOnline Database - Provo, UT, USA. Ancestry.com\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nEdmund West\n</p><p>\n<b>\nPublication information: \n</b>\nOnline Database - Provo, UT, USA. Ancestry.com\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nEdson S. Packer\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nIda M. Rollins\n</p>",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nJames Rollins\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJames Rutheford\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Bradshaw\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Bradshaw\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Spilsbury Bradshaw\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Spilsbury\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Spilsbury\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Spilsbury\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Spilsbury\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nJanet Spilsbury\n</p>",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nLizzie Poll Berret & Ida Berrett Poll\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nMadge Summers Newton\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nMarcia Durfee Chisholm\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nRobert L. Hamblin and Lorene Bradshaw\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nRobert L. Hamblin\n</p><p>\n<b>\nPublication information: \n</b>\n7-28-06\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nRuby Summers\n</p><p>\n<b>\nPublication information: \n</b>\nFebruary 1940\n</p>",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nThe Church of Jesus Christ of Latter Day Saints\n</p><p>\n<b>\nPublication information: \n</b>\nhttps://history.churchofjesuschrist.org/overlandtravel/?lang=eng\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nThe Media Research Bureau\n</p><p>\n<b>\nPublication information: \n</b>\nWashington D.C.\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_S_text_0.js');
