// This file is generated

I_birth_place_0 = [
"",
"",
"Lewiston, Cache, Utah, United States of America",
"Lisbon, Grafton, New Hampshire, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Saint Charles, St. Charles, Missouri, United States of America",
"",
"",
"",
"Mansfield, Nottinghamshire, East Midlands, England",
"Alameda, Alameda, California, United States of America",
"Derby, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"",
"Derby, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Hope, Derbyshire, East Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"Old Monkland, Lanarkshire, Scotland",
"",
"",
"",
"",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Granville, Hampden, Massachusetts, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Heber's Spring, Platte, Wyoming, New York, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Bountiful, Davis, Utah, United States of America",
"March, Cambridgeshire, East, England",
"Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bethel, Oxford, Maine, United States of America",
"Shamokin, Northumberland, Pennsylvania, United States of America",
"Putnam, Windham, Connecticut, United States of America",
"Germany",
"Albany, Wyoming, New York, United States of America",
"Dalbury, Derbyshire, East Midlands, England",
"Litchfield, Litchfield, Connecticut, United States of America",
"",
"",
"Huntington, Lorain, Ohio, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Lyman, Uinta, Wyoming, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Derbyshire, East Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Staffordshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Ilkeston, Derbyshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Bedford, Bedfordshire, East, England",
"Cossall, Nottinghamshire, East Midlands, England",
"Sneinton, Nottinghamshire, East Midlands, England",
"Ilkeston, Derbyshire, East Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Ilkeston, Derbyshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Ilkeston, Derbyshire, East Midlands, England",
"Derby, Derbyshire, East Midlands, England",
"Lyman, Uinta, Wyoming, United States of America",
"Clayton le Moors, Lancashire, North West, England",
"Cuddington, Buckinghamshire, South East, England",
"Worcester, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"Suckley, Worcestershire, West Midlands, England",
"",
"Hartland, Niagara, New York, United States of America",
"Kanesville, Pottawattamie, Iowa, United States of America",
"",
"New York, United States of America",
"New York, United States of America",
"Arbory, Isle of Man",
"",
"",
"",
"",
"",
"",
"",
"Madison Township, Geauga, Ohio, United States of America",
"Willow Creek, Box Elder, Utah, United States of America",
"Willow Creek, Box Elder, Utah, United States of America",
"",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Afton, Uinta, Wyoming, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"",
"",
"",
"",
"Quorn, Leicestershire, East Midlands, England",
"Markfield, Leicestershire, East Midlands, England",
"Liverpool, Lancashire, North West, England",
"Quorn, Leicestershire, East Midlands, England",
"Dublin, Dublin, Leinster, Ireland",
"Jacksonville, Duval, Florida, United States of America",
"Quorn, Leicestershire, East Midlands, England",
"Markfield, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Liverpool, Lancashire, North West, England",
"Quorn, Leicestershire, East Midlands, England",
"Markfield, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Liverpool, Lancashire, North West, England",
"Quorn, Leicestershire, East Midlands, England",
"Markfield, Leicestershire, East Midlands, England",
"Chattanooga, Hamilton, Tennessee, United States of America",
"Liverpool, Lancashire, North West, England",
"Kilby, Leicestershire, East Midlands, England",
"Jacksonville, Duval, Florida, United States of America",
"Chattanooga, Hamilton, Tennessee, United States of America",
"Markfield, Leicestershire, East Midlands, England",
"Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Brixton, Lambeth, Surrey, London, England",
"London, London, England",
"London, London, England",
"London, London, England",
"Westminster, London, England",
"Bedford, Bedfordshire, East, England",
"Pimlico, Middlesex, South East, England",
"Clapham Common, London, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Pimlico, Middlesex, South East, England",
"Bedford, Bedfordshire, East, England",
"Holborn, Middlesex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"",
"Louth, Lincolnshire, East Midlands, England",
"Bedford, Bedfordshire, East, England",
"",
"",
"",
"Far West, Caldwell, Missouri, United States of America",
"Fort Ann, Washington, New York, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Fort Ann, Washington, New York, United States of America",
"Florence, Erie, Ohio, United States of America",
"Liberty, Clay, Missouri, United States of America",
"Galon, Washington, New York, United States of America",
"Queensbury, Warren, New York, United States of America",
"Fort Ann, Washington, New York, United States of America",
"Galvin, New York, United States of America",
"",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Stowell, Somerset, South West England, England",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"",
"Stockport, Cheshire, North West, England",
"Chipping, Lancashire, North West, England",
"Nauvoo, Hancock, Illinois, United States of America",
"Thornley, Lancashire, North West, England",
"Thornley, Lancashire, North West, England",
"Thornley, Lancashire, North West, England",
"Lezayre, Ayre, Isle of Man",
"Isle of Man",
"",
"Isle of Man",
"Patrick, Isle of Man",
"Ballaugh, Michael, Isle of Man",
"Kirk Michael, Michael, Isle of Man",
"Isle of Man",
"Isle of Man",
"Kirk Michael, Michael, Isle of Man",
"Isle of Man",
"Kirk Michael, Michael, Isle of Man",
"Isle of Man",
"Ballaugh, Michael, Isle of Man",
"Mercer, Kentucky, United States of America",
"Rockville, Parke, Indiana, United States of America",
"Kentucky, United States of America",
"Mercer, Kentucky, United States of America",
"Illinois, United States of America",
"Kentucky, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Indiana, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"Norfolk, Litchfield, Connecticut, United States of America",
"Norfolk, Litchfield, Connecticut, United States of America",
"Harwinton, Litchfield, Connecticut, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"Norfolk, Litchfield, Connecticut, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"New York, United States of America",
"Norfolk, Litchfield, Connecticut, United States of America",
"Norfolk, Litchfield, Connecticut, United States of America",
"Genesee, New York, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"New Brunswick, Middlesex, New Jersey, United States of America",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Louth, Lincolnshire, East Midlands, England",
"Lincolnshire, East Midlands, England",
"Oneida, Idaho, United States of America",
"Weston, Franklin, Idaho, United States of America",
"Halifax, Yorkshire, Yorkshire and the Humber, England",
"Oneida, Idaho, United States of America",
"Weston, Franklin, Idaho, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Springville, Utah, Utah, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Kinderhook, Columbia, New York, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Kingsbury, Washington, New York, United States of America",
"Kingsbury, Washington, New York, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Highgate, Middlesex, South East, England",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"Rutland Township, Tioga, Pennsylvania, United States of America",
"Sullivan Township, Tioga, Pennsylvania, United States of America",
"",
"Bolton, Warren, New York, United States of America",
"",
"",
"",
"",
"Allegany, Cattaraugus, New York, United States of America",
"Pike, Wyoming, New York, United States of America",
"Pike, Wyoming, New York, United States of America",
"Wyoming, New York, United States of America",
"Wethersfield, Wyoming, New York, United States of America",
"",
"",
"",
"",
"",
"",
"Amboy, Oswego, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Caineville, Wayne, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Aldridge, Wayne, Utah, United States of America",
"Caineville, Wayne, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Springville, Utah, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Tiverton, Newport, Rhode Island, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Amboy, Oswego, New York, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Amboy, Oswego, New York, United States of America",
"Williamstown, Oswego, New York, United States of America",
"Tiverton, Newport, Rhode Island, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Springville, Utah, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Amboy, Oswego, New York, United States of America",
"Lyman, Wayne, Utah, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Kirtland, Lake, Ohio, United States of America",
"Colonia Dublan, Nuevo Casas Grandes, Chihuahua, Mexico",
"Aldridge, Wayne, Utah, United States of America",
"Aurora, Sevier, Utah, United States of America",
"Aldridge, Wayne, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Lenox, Madison, New York, United States of America",
"Loa, Wayne, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Amboy, Oswego, New York, United States of America",
"",
"Almy, Uinta, Wyoming, United States of America",
"Polmont, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Bathgate, Linlithgowshire, Scotland",
"Spring Valley, Uinta, Wyoming, United States of America",
"Spring Valley, Uinta, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Diamondville, Uinta, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Polmont, Stirlingshire, Scotland",
"Almy, Uinta, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Wallacestone, Stirlingshire, Scotland",
"Inveresk, Midlothian, Scotland",
"Almy, Uinta, Wyoming, United States of America",
"Almy, Uinta, Wyoming, United States of America",
"Uinta, Wyoming, United States of America",
"Glencoe, Lincoln, Wyoming, United States of America",
"Wallacestone, Stirlingshire, Scotland",
"Almy, Uinta, Wyoming, United States of America",
"",
"",
"",
"Edmonton, Middlesex, South East, England",
"",
"",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Quarrington, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Greenville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Greenville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Quarrington, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"Dowsby, Lincolnshire, East Midlands, England",
"",
"",
"",
"",
"Draper, Salt Lake, Utah, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Monongahela, Washington, Pennsylvania, United States of America",
"Butler, Ohio, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Danville, Vermillion, Illinois, United States of America",
"Monongahela, Washington, Pennsylvania, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Georges Township, Fayette, Pennsylvania, United States of America",
"Monongahela, Washington, Pennsylvania, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Redstone, Fayette, Pennsylvania, United States of America",
"Millcreek, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"",
"Sterling, Windham, Connecticut, United States of America",
"Wield, Hampshire, South East, England",
"Chester, Delaware, Pennsylvania, United States of America",
"",
"Lincolnshire, East Midlands, England",
"East Greenwich, Kent, Rhode Island, United States of America",
"",
"Leigh, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"",
"Derby, Derbyshire, East Midlands, England",
"",
"Amenia, Dutchess, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Moravia, Cayuga, New York, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Stanford, Dutchess, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Dutchess, New York, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Dutchess, New York, United States of America",
"Stanford, Dutchess, New York, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Winter Quarters, Douglas, Nebraska, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Dutchess, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Poughkeepsie, Dutchess, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Windham Grove, Greene, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"East Fishkill, Dutchess, New York, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Cedar City, Iron, Utah, United States of America",
"Stanford, Dutchess, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Cedar City, Iron, Utah, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Minersville, Beaver, Utah, United States of America",
"Munson Township, Geauga, Ohio, United States of America",
"Munson Township, Geauga, Ohio, United States of America",
"Lyman, Uinta, Wyoming, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bainbridge, Ross, Ohio, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"North Hero, Grand Isle, Vermont, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Franklin, Walworth, Wisconsin, United States of America",
"Spring Prairie, Walworth, Wisconsin, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Falmouth, Barnstable, Massachusetts, United States of America",
"Conneaut, Ashtabula, Ohio, United States of America",
"Cumberland, Lincoln, Wyoming, United States of America",
"Glencoe, Lincoln, Wyoming, United States of America",
"Lyman, Uinta, Wyoming, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"North Hero, Grand Isle, Vermont, United States of America",
"Fowlers Mill, Geauga, Ohio, United States of America",
"Munson Township, Geauga, Ohio, United States of America",
"Bainbridge, Ross, Ohio, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Santa Clara, Washington, Utah, United States of America",
"Bainbridge, Ross, Ohio, United States of America",
"Tysoe, Warwickshire, West Midlands, England",
"Quarrington, Lincolnshire, East Midlands, England",
"Quarrington, Lincolnshire, East Midlands, England",
"Silk Willoughby, Lincolnshire, East Midlands, England",
"Quarrington, Lincolnshire, East Midlands, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Holiston, Middlesex, South East, England",
"North Hero, Grand Isle, Vermont, United States of America",
"Lichfield, Staffordshire, West Midlands, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Windsor, Kennebec, Maine, United States of America",
"",
"Wethersfield, Wyoming, New York, United States of America",
"Genessee, Allegany, New York, United States of America",
"",
"Prestonpans, Haddingtonshire, Scotland",
"Old Monkland, Lanarkshire, Scotland",
"Armadale, Linlithgowshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"Newton, Midlothian, Scotland",
"Bathgate, Linlithgowshire, Scotland",
"Newton, Midlothian, Scotland",
"Midlothian, Scotland",
"Claybarns, Midlothian, Scotland",
"Wilton, Roxburghshire, Scotland",
"Claybarns, Midlothian, Scotland",
"Cockmalane, Midlothian, Scotland",
"Cadder, Lanarkshire, Scotland",
"West Calder, Edinburghshire, Scotland",
"Claybarns, Midlothian, Scotland",
"Claybarns, Midlothian, Scotland",
"Kilwinning, Ayrshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"Newton, Midlothian, Scotland",
"Prestonpans, Haddingtonshire, Scotland",
"West Calder, Linlithgowshire, Scotland",
"Claybarns, Midlothian, Scotland",
"Edinburgh, Midlothian, Scotland",
"West Calder, Linlithgowshire, Scotland",
"East Benhar, Linlithgowshire, Scotland",
"Claybarns, Midlothian, Scotland",
"",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"",
"",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Westbourne, Sussex, South East, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Yorkshire, Yorkshire and the Humber, England",
"Yorkshire, Yorkshire and the Humber, England",
"Wythall, Worcestershire, West Midlands, England",
"",
"Amenia, Dutchess, New York, United States of America",
"Goshen, Orange, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Goshen, Orange, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Goshen, Orange, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Amenia, Dutchess, New York, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Kings Norton, Worcestershire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Aston, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Redford, Wayne, Michigan, United States of America",
"New York, United States of America",
"Redford, Wayne, Michigan, United States of America",
"New York, United States of America",
"Michigan, United States of America",
"Dutchess, New York, United States of America",
"Dukinfield, Cheshire, North West, England",
"",
"",
"",
"",
"",
"",
"",
"Torrington, Litchfield, Connecticut, United States of America",
"Watertown, Jefferson, New York, United States of America",
"Jefferson, New York, United States of America",
"Torrington, Litchfield, Connecticut, United States of America",
"Watertown, Jefferson, New York, United States of America",
"",
"Lyonshall, Herefordshire, West Midlands, England",
"Nashville, Davidson, Tennessee, United States of America",
"",
"",
"",
"",
"",
"",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Oxford, Bannock, Idaho, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Royalston, Worcester, Massachusetts, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Lockport, Niagara, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Springville, Utah, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"",
"",
"",
"",
"",
"Suffield, Portage, Ohio, United States of America",
"Wakefield, Yorkshire, Yorkshire and the Humber, England",
"Sheldon, Franklin, Vermont, United States of America",
"Shepshed, Leicestershire, East Midlands, England",
"",
"",
"",
"",
"",
"Kirk Michael, Michael, Isle of Man",
"",
"",
"",
"",
"",
"Bulwell, Nottinghamshire, East Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Wymondham, Norfolk, East, England",
"",
"Kilmarnock, Ayrshire, Scotland",
"",
"Lockport, Niagara, New York, United States of America",
"Castleton, Derbyshire, East Midlands, England",
"Castleton, Derbyshire, East Midlands, England",
"Derbyshire, East Midlands, England",
"",
"Castleton, Derbyshire, East Midlands, England",
"",
"Castleton, Derbyshire, East Midlands, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Castleton, Derbyshire, East Midlands, England",
"Castleton, Derbyshire, East Midlands, England",
"",
"",
"",
"Crawfordsburn, County Down, Ireland",
"Des Moines, Polk, Iowa, United States of America",
"",
"",
"",
"",
"",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Prescott, Ontario, Canada",
"Spanish Fork, Utah, Utah, United States of America",
"",
"Fayetteville, Fayette, Georgia, United States of America",
"Montgomery, New York, United States of America",
"Florida, Montgomery, New York, United States of America",
"",
"",
"",
"",
"",
"",
"",
"Heckington, Lincolnshire, East Midlands, England",
"",
"Heckington, Lincolnshire, East Midlands, England",
"",
"Donington, Lincolnshire, East Midlands, England",
"Donington, Lincolnshire, East Midlands, England",
"",
"Heckington, Lincolnshire, East Midlands, England",
"Helpringham, Lincolnshire, East Midlands, England",
"",
"",
"",
"Suckley, Worcestershire, West Midlands, England",
"Faskine, Lanarkshire, Scotland",
"Calderbank, Lanarkshire, Scotland",
"Carnbroe, Lanarkshire, Scotland",
"Calderbank, Lanarkshire, Scotland",
"Lanarkshire, Scotland",
"Motherwell, North Lanarkshire, Scotland",
"Beith, Ayrshire, Scotland",
"Calderbank, Lanarkshire, Scotland",
"Wilsontown, Lanarkshire, Scotland",
"New Monkland, Lanarkshire, Scotland",
"",
"Longford, Derbyshire, East Midlands, England",
"Montpelier, Bear Lake, Idaho, United States of America",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Quorn, Leicestershire, East Midlands, England",
"Blooming Grove, Orange, New York, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Winter Quarters, Douglas, Nebraska, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Rahway, Essex, New Jersey, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Logan, Cache, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Salt Lake City, Salt Lake, Utah, United States of America",
"West Bountiful, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kirtland, Lake, Ohio, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Bountiful, Davis, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Woods Cross, Davis, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Saint John, St. John, New Brunswick, Canada",
"Saint John, St. John, New Brunswick, Canada",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Woods Cross, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Watertown, Jefferson, New York, United States of America",
"Laie, Oahu, Hawaii, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Kamas, Summit, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"",
"Amenia, Dutchess, New York, United States of America",
"Newmarket, Flintshire, Wales",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"Saint Asaph, Denbighshire, Wales",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"England",
"Pimlico, Middlesex, South East, England",
"Monongahela, Washington, Pennsylvania, United States of America",
"Stone Arabia, Montgomery, New York, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Wymondham, Norfolk, East, England",
"Grafton, Washington, Utah, United States of America",
"Lowestoft, Suffolk, East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Great Ellingham, Norfolk, East, England",
"Saint George, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Deopham, Norfolk, East, England",
"Wymondham, Norfolk, East, England",
"Almeley, Herefordshire, West Midlands, England",
"Almeley, Herefordshire, West Midlands, England",
"Hereford, Herefordshire, West Midlands, England",
"Herefordshire, West Midlands, England",
"Pembridge, Herefordshire, West Midlands, England",
"Kings Pyon, Herefordshire, West Midlands, England",
"",
"Herefordshire, West Midlands, England",
"Almeley, Herefordshire, West Midlands, England",
"Horsley, Gloucester, South West England, England",
"Sheffield, Yorkshire, Yorkshire and the Humber, England",
"Arbory, Isle of Man",
"Malew, Isle of Man",
"Liverpool, Lancashire, North West, England",
"Malew, Isle of Man",
"Malew, Isle of Man",
"Liverpool, Lancashire, North West, England",
"Malew, Isle of Man",
"Malew, Isle of Man",
"Liverpool, Lancashire, North West, England",
"",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"Dalbury, Derbyshire, East Midlands, England",
"Longford, Derbyshire, East Midlands, England",
"West Newark, Essex, New Jersey, United States of America",
"Birmingham, Warwickshire, West Midlands, England",
"",
"Quorn, Leicestershire, East Midlands, England",
"",
"",
"Ruabon, Denbighshire, Wales",
"Ruabon, Denbighshire, Wales",
"Saint Pancras, London, London, England",
"Rhosllanerchrugog, Denbighshire, Wales",
"Ruabon, Denbighshire, Wales",
"Ruabon, Denbighshire, Wales",
"Ruabon, Denbighshire, Wales",
"Saint Pancras, London, London, England",
"Saint Pancras, London, London, England",
"Rhosllanerchrugog, Denbighshire, Wales",
"Ruabon, Denbighshire, Wales",
"Onondaga Hill, Onondaga, New York, United States of America",
"",
"",
"",
"Minersville, Beaver, Utah, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Lima, Livingston, New York, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Parowan, Iron, Utah, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Alton, Souix, Iowa, United States of America",
"Beaver, Beaver, Utah, United States of America",
"Lima, Livingston, New York, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Missouri, United States of America",
"Dublin, Cheshire, New Hampshire, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Minersville, Beaver, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Lima, Livingston, New York, United States of America",
"San Bernardino, San Bernardino, California, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Edmonton, Middlesex, South East, England",
"Rock Hill, Worcestershire, West Midlands, England",
"Warbleton, Sussex, South East, England",
"Killin, Perthshire, Scotland",
"",
"",
"",
"",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Newton, Midlothian, Scotland",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Watford, Hertfordshire, East, England",
"Cradley, Herefordshire, West Midlands, England",
"Hereford, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Sempronius, Cayuga, New York, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Saunders, Nebraska, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"St. Louis, St. Louis, Missouri, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Clifton on Teme, Worcestershire, West Midlands, England",
"Leigh, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Nauvoo, Hancock, Illinois, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Leigh, Worcestershire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Draper, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Springdale, Washington, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Nauvoo, Hancock, Illinois, United States of America",
"Grafton, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"St. Joseph, Buchanan, Missouri, United States of America",
"Draper, Salt Lake, Utah, United States of America",
"Cradley, Herefordshire, West Midlands, England",
"Toquerville, Washington, Utah, United States of America",
"Toquerville, Washington, Utah, United States of America",
"Leigh, Worcestershire, West Midlands, England",
"Cradley, Herefordshire, West Midlands, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Florida, Montgomery, New York, United States of America",
"New York, United States of America",
"Dover, Kent, South East, England",
"Forfar, Angus, Scotland",
"",
"",
"",
"Mount Pisgah, Union, Iowa, United States of America",
"",
"",
"",
"",
"",
"Wotton Under Edge, Gloucester, South West England, England",
"Donington, Lincolnshire, East Midlands, England",
"Mercer, Kentucky, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Heathfield, Sussex, South East, England",
"Brighton, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Heathfield, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Brighton, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Brighton, Sussex, South East, England",
"Salt Lake City, Salt Lake, Utah, United States of America",
"",
"Bountiful, Davis, Utah, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Bountiful, Davis, Utah, United States of America",
"Rush Valley, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Rush Valley, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Rockland, Knox, Maine, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Riverdale, Franklin, Idaho, United States of America",
"Augusta, Kennebec, Maine, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Salt Lake City, Salt Lake, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Tooele, Tooele, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Chesterfield, Caribou, Idaho, United States of America",
"Council Bluffs, Pottawattamie, Iowa, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Punka Camp, Pottawattamie, Iowa, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bishops Frome, Herefordshire, West Midlands, England",
"Kniveton, Derbyshire, East Midlands, England",
"",
"",
"",
"",
"",
"Cradley, Herefordshire, West Midlands, England",
"Manchester, Lancashire, North West, England",
"Essex, Essex, New York, United States of America",
"Dayton, Montgomery, Ohio, United States of America",
"Winchester, Randolph, Indiana, United States of America",
"New York, New York, New York, United States of America",
"New York, New York, New York, United States of America",
"Essex, New Jersey, United States of America",
"Essex, Essex, New York, United States of America",
"Essex, Essex, New York, United States of America",
"St. Helier, Jersey",
"Dayton, Montgomery, Ohio, United States of America",
"Manhattan, New York, New York, New York, United States of America",
"Essex, Essex, New York, United States of America",
"New York, New York, New York, United States of America",
"Pennsylvania, United States of America",
"Thornley, Lancashire, North West, England",
"",
"",
"",
"Bountiful, Davis, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Bountiful, Davis, Utah, United States of America",
"Augusta, Kennebec, Maine, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Woodruff, Rich, Utah, United States of America",
"Cradley, Herefordshire, West Midlands, England",
"",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Edmonton, Middlesex, South East, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Stratford-Upon-Avon, Warwickshire, West Midlands, England",
"Stratford-Upon-Avon, Warwickshire, West Midlands, England",
"Birmingham, Warwickshire, West Midlands, England",
"Alfreton, Derbyshire, East Midlands, England",
"Shipley, Derbyshire, East Midlands, England",
"Derbyshire, East Midlands, England",
"Bulwell, Nottinghamshire, East Midlands, England",
"North Wingfield, Derbyshire, East Midlands, England",
"Hucknall Torkard, Nottinghamshire, East Midlands, England",
"Hucknall Torkard, Nottinghamshire, East Midlands, England",
"Wallingwells, Nottinghamshire, East Midlands, England",
"",
"Bridgewater, Plymouth, Massachusetts, United States of America",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Newmarket, Flintshire, Wales",
"Caerwys, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Tremeirchion, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Tremeirchion, Flintshire, Wales",
"Coalville, Summit, Utah, United States of America",
"Newmarket, Flintshire, Wales",
"Eglwys Fach, Denbighshire, Wales",
"Cwm, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Mold, Flintshire, Wales",
"Coalville, Summit, Utah, United States of America",
"Graig, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Tremeirchion, Flintshire, Wales",
"Tremeirchion, Flintshire, Wales",
"Newmarket, Flintshire, Wales",
"Cwm, Flintshire, Wales",
"Tremeirchion, Flintshire, Wales",
"Flintshire, Wales",
"Old Cotes, Nottinghamshire, East Midlands, England",
"",
"Hebron, Washington, New York, United States of America",
"",
"Cambridge, Cambridgeshire, East, England",
"Markfield, Leicestershire, East Midlands, England",
"Airdrie, Lanarkshire, Scotland",
"Castleton, Derbyshire, East Midlands, England",
"Cradley, Herefordshire, West Midlands, England"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
