// This file is generated

S_author_0 = [
"Ruby Summers",
"Marcia Durfee Chisholm",
"Darrell E. Chisholm",
"Darrell E. Chisholm",
"Dora D. Flack",
"Ida M. Rollins",
"James Rollins",
"Albert Edward Woolley Chisholm",
"Janet Spilsbury Bradshaw",
"Robert L. Hamblin and Lorene Bradshaw",
"Robert L. Hamblin",
"",
"Edmund West",
"",
"",
"Janet Spilsbury",
"Darrell or Marcia Chisholm",
"The Media Research Bureau",
"Janet Bradshaw",
"",
"",
"Janet Spilsbury",
"Janet Spilsbury",
"",
"",
"Edmund West",
"Janet Spilsbury",
"",
"",
"Cecilia Arthema Durfee Tolman",
"",
"Edson S. Packer",
"Janet Bradshaw",
"",
"",
"Charles Rendell Mabey",
"Brother Harward",
"Caroline Richards Woodall Howard",
"",
"Madge Summers Newton",
"",
"",
"The Church of Jesus Christ of Latter Day Saints",
"",
"James Rutheford",
"",
"",
"",
"Lizzie Poll Berret & Ida Berrett Poll",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Janet Spilsbury",
"Beatrice Easton Alleman"
]
Dwr.ScriptLoaded('dwr_db_S_author_0.js');
